### ISSUE TITLE
Unable to build x64  nodejs

### ISSUE THREAD

**Issue by AdamMachera** [Azure/azure-iot-gateway-sdk#144] opened 2017-03-02 11:21 UTC
I'm unable to build x64 nodejs.
I took today latest master.
I executed 
build_nodejs.cmd
build.cmd --platform x64 --config Release --disable-ble-module --enable-nodejs-binding

I'm getting exception:

       "c:\s\azure-iot-gateway-sdk\build\azure_iot_gateway_sdk.sln" (default target) (1) ->
       "c:\s\azure-iot-gateway-sdk\build\bindings\nodejs\nodejs_binding.vcxproj.metaproj" (default target) (18) ->
       "c:\s\azure-iot-gateway-sdk\build\bindings\nodejs\nodejs_binding.vcxproj" (default target) (35) ->
       (Link target) ->
         node.lib(node.dll) : fatal error LNK1112: module machine type 'X86' conflicts with target machine type 'x64' [
       c:\s\azure-iot-gateway-sdk\build\bindings\nodejs\nodejs_binding.vcxproj]

    12 Warning(s)
    1 Error(s)

I have added detailed log into attached file.

Thanks,
Adam.
[buildlog.txt](https://github.com/Azure/azure-iot-gateway-sdk/files/813602/buildlog.txt)

**Comment by avranju** [comment] 2017-03-02 18:46
The issue is that `build_nodejs.cmd` builds x86 bits by default and you're attempting to build a 64 bit version of the gateway SDK which tries to link with the Node.js library files. You'll want to build a 64 bit version of Node.js as well. Can you try running `build_nodejs.cmd` like so please?

```
tools\build_nodejs.cmd x64
```

**Comment by damonbarry** [comment] 2017-03-07 19:24
Adam confirmed that his question was answered, closing...

**Closed by damonbarry** 2017-03-07 19:24 UTC
Labels: question
