### ISSUE TITLE
UWP Example

### ISSUE THREAD

**Issue by ddobric** [Azure/azure-iot-gateway-sdk#212] opened 2017-04-14 09:36 UTC
Hi all,

do we have somewhere in the repo an UWP example?
I have built dotnet core example and tried to reference required assemblies from UWP app. It crashes without any meaningful error on start of the app.
This usually indicates that some referenced assemblies are incompatible.

Thanks

**Comment by aribeironovaes** [comment] 2017-04-14 17:28
HI @ddobric, 

It's on the list of enhancement: https://github.com/Azure/azure-iot-gateway-sdk/issues/47
UWP not supported yet. 
But feel free to dig in and submit a PR for UWP support. 

Thanks, 

Angelo Ribeiro.

**Comment by damonbarry** [comment] 2017-04-20 18:32
Duplicate of #47. Closing...

**Closed by damonbarry** 2017-04-20 18:32 UTC
